### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Andersos** [krishnavteja/ReactNodeReadingList#1]
Hey, I tried running your reading list. It would be nice to update the Readme to say that you need to run MongoDB before starting the app. It is also usually smart to not check in the node_modules folders because the dependencies are built for the platform you are on. You can do that by adding the folder to the Git ignore list http://git-scm.com/docs/gitignore. I had to delete and redownload all of the dependencies.

**Comment by krishnavteja** [comment]
Hi Andersos,

Thanks for the feedback. I am very new to git and I am still learning. Thanks for pointing out about the node_modules folder. When I first researched about this, I found articles which said either case is fine (checking in and not checking in the npm files). But I am seeing more and more people advising against it now. I fixed it and I am now ignoring the node_modules.

Also, I did write up some instructions in Readme file a couple days back and couldn't get the formatting right and so rolled it back. I was able to figure it out today. 

Thanks again for your feedback. I learned some important things today :)

**Comment by Andersos** [comment]
Great! Keep up the good work. 

If you are having trouble with the formatting in the readme then check out this resource https://help.github.com/articles/github-flavored-markdown/

Maybe you should add a name, version, description and some scripts to your main `package.json`. 
You could add the start script `gulp` if that is what you like. Here is more information. https://docs.npmjs.com/files/package.json.

Im closing this since you fixed my feedback but let me know if there is anything.
Let me know if you have any questions. I might be able to help.

**Comment by krishnavteja** [comment]
Thanks. Will reach out if I have any questions.
